export function formatAIComment(result) {
  let comment = `## 🤖 AI Cost Optimizer

### 📊 Cost Analysis

| Metric | Value |
|---|---:|
| Current Cost | $${result.currentCost} |
| Potential Savings | $${result.estimatedSavings} |
| Possible Reduction | ${result.savingsPercentage}% |

### 💡 AI Recommendations

${result.summary}
`;

  if (
    result.recommendations?.length
  ) {
    result.recommendations.forEach(
      (recommendation, index) => {
        comment += `

---

### ${index + 1}. ${
          recommendation.title
        }

**Impact:** ${recommendation.impact}

${recommendation.description}

💰 **Estimated savings:** $${recommendation.estimatedSavings}
`;

        if (recommendation.workflow) {
          comment += `

**Workflow:** \`${recommendation.workflow}\`
`;
        }

        if (recommendation.yaml) {
          comment += `

<details>
<summary>🔧 Suggested YAML Fix</summary>

\`\`\`yaml
${recommendation.yaml}
\`\`\`

</details>
`;
        }
      }
    );
  }

  comment += `

---

> Generated by **GitHub Cost Analyzer AI** using OpenRouter + Nemotron.
`;

  return comment;
}
