export function formatRecommendationComment(rec) {
  const icon = rec.impact === "high" ? "🔴 Major" :
               rec.impact === "medium" ? "🟡 Medium" : "🟢 Minor";

  let suggestedCode = "";
  const fixCode = rec.suggestedCode || rec.codeFix || rec.yaml;
  if (typeof fixCode === "string") {
    suggestedCode = fixCode;
  } else if (Array.isArray(fixCode)) {
    suggestedCode = fixCode.join("\n");
  }

  let body = `### ⚠️ Potential cost optimization | ${icon}

**${rec.title}**

${rec.description}

💰 **If you optimize this, you save:** $${rec.estimatedSavings || 0}/mo
`;

  if (suggestedCode) {
    body += `
<details>
<summary>▶️ Committable suggestion</summary>

\`\`\`suggestion
${suggestedCode}
\`\`\`

</details>
`;
  }

  return body;
}

export function formatAIComment(result) {
  let comment = `## 🪙 Coin Care
 
### 📊 Cost Analysis
 
| Metric | Value |
|---|---:|
| Current Cost | $${result.currentCost} |
| Potential Savings | $${result.estimatedSavings} |
| Possible Reduction | ${result.savingsPercentage}% |
 
### 💡 Coin Care Recommendations
 
${result.summary}
`;

  comment += `

---

> Generated by **Coin Care** (built by Viraj Koradia).
`;

  return comment;
}
