export function formatAIComment(result) {
  let comment = `## 🪙 Coin Care
 
### 📊 Cost Analysis
 
| Metric | Value |
|---|---:|
| Current Cost | $${result.currentCost} |
| Potential Savings | $${result.estimatedSavings} |
| Possible Reduction | ${result.savingsPercentage}% |
 
### 💡 Coin Care Recommendations
 
${result.summary}
`;

  if (result.recommendations?.length) {
    result.recommendations.forEach((recommendation, index) => {
      const file = recommendation.filePath || recommendation.workflow;
      
      let originalLines = [];
      if (typeof recommendation.originalCode === "string") {
        originalLines = recommendation.originalCode.split(/\r?\n/);
      } else if (Array.isArray(recommendation.originalCode)) {
        originalLines = recommendation.originalCode;
      }

      let suggestedLines = [];
      const fixCode = recommendation.suggestedCode || recommendation.codeFix || recommendation.yaml;
      if (typeof fixCode === "string") {
        suggestedLines = fixCode.split(/\r?\n/);
      } else if (Array.isArray(fixCode)) {
        suggestedLines = fixCode;
      }

      const startLine = Number(recommendation.startLine) || 1;
      const context = recommendation.lineContext || "";
      const originalCount = originalLines.length;
      const suggestedCount = suggestedLines.length;

      let hunkHeader = "";
      if (originalCount > 0 || suggestedCount > 0) {
        hunkHeader = `@@ -${startLine},${originalCount} +${startLine},${suggestedCount} @@${context ? " " + context : ""}\n`;
      }

      let diffContent = hunkHeader;
      if (originalCount > 0) {
        diffContent += originalLines.map(line => `-${line}`).join("\n");
      }
      if (suggestedCount > 0) {
        if (originalCount > 0) diffContent += "\n";
        diffContent += suggestedLines.map(line => `+${line}`).join("\n");
      }

      const icon = recommendation.impact === "high" ? "🔴 Major" :
                   recommendation.impact === "medium" ? "🟡 Medium" : "🟢 Minor";

      comment += `

---

> ### ⚠️ Potential cost optimization | ${icon}
>
> **${recommendation.title}**
>
> 💰 **If you optimize this, you save:** $${recommendation.estimatedSavings || 0}/mo
>
> ${recommendation.description}
`;

      if (file) {
        comment += `>
> **File:** \`${file}\`
`;
      }

      if (diffContent) {
        comment += `
<details>
<summary>▶️ Committable suggestion</summary>

\`\`\`diff
${diffContent}
\`\`\`

</details>
`;
      }
    });
  }

  comment += `

---

> Generated by **Coin Care** (built by Viraj Koradia).
`;

  return comment;
}
