name: Cost Optimizer

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  cost-analysis:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Generate Bot Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Run AI Cost Optimizer
        uses: viraj0075/github-cost-optimizer@main
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          fail-on: none
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_MODEL: google/gemini-2.5-flash
          OPENROUTER_URL: https://openrouter.ai/api/v1/chat/completions
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}